### PR TITLE
Issue #2987846 by daniel.bosen, mtodor: The preselection of the default view mode is annoying

### PR DESCRIPTION
**Pull request by mtodor**

### CODE REVIEW

**Comment by dbosen** [comment]
After discussing this approach, we came to the conclusion, that the Custom Display Settings would be the better place to select the default display

**Review by dbosen — CHANGES_REQUESTED** [review]
see previous comment

**Review by chrfritsch — COMMENTED** [review]
I checked the functionality and it works. Also the code looks fine.

I just wanted to say that I think the setting might be better placed on the source list. It feels a bit odd, that you define the view mode, that is used for source lists in "Manage display".

**Review by dbosen — APPROVED** [review]
We keep the settings where they are now.

**Pull request merged**
